version: "3.7"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: astu-guide:v1
    environment:
      - PORT=8020
    env_file:
      - web/web/.env
    ports:
      - "8005:8020"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - ./staticfiles:/app/staticfiles/